# Generated by Django 3.2.4 on 2021-07-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_categories',
            name='category',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Show', 'Show'), ('Webseries', 'Webseries'), ('Kids', 'Kids')], max_length=500),
        ),
        migrations.AlterField(
            model_name='add_categories',
            name='geners',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Thirller', 'Thirller'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Sci Fi', 'Sci Fi')], max_length=500),
        ),
        migrations.AlterField(
            model_name='add_categories',
            name='language',
            field=models.CharField(choices=[('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'), ('Malayalam', 'Malayalam'), ('Kannada', 'Kannada'), ('English', 'English')], max_length=500),
        ),
        migrations.AlterField(
            model_name='add_categories',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve')], default='Pending', max_length=500),
        ),
    ]
