# Generated by Django 3.2.4 on 2021-07-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_auto_20210722_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_categories',
            name='Publisher_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
