# Generated by Django 3.2.4 on 2021-07-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_add_categories_publisher_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_categories',
            old_name='Publisher_name',
            new_name='publisher_name',
        ),
    ]
