# Generated by Django 3.2.4 on 2021-06-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('premium', models.BooleanField(default=False)),
                ('discription', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnail_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('background_image_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('screen_shot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('screen_shot_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('movie_length', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_director', models.CharField(blank=True, max_length=200, null=True)),
                ('movie_actor', models.CharField(blank=True, max_length=1000, null=True)),
                ('movie_language', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_type', models.CharField(blank=True, max_length=200, null=True)),
                ('movie_category', models.CharField(blank=True, max_length=100, null=True)),
                ('link_4k', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_1920', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_720', models.CharField(blank=True, max_length=1000, null=True)),
                ('size_4k', models.CharField(blank=True, max_length=1000, null=True)),
                ('size_1920', models.CharField(blank=True, max_length=1000, null=True)),
                ('size_720', models.CharField(blank=True, max_length=1000, null=True)),
                ('movie_link', models.TextField(blank=True, max_length=10000, null=True)),
                ('movie_online', models.TextField(blank=True, max_length=1000, null=True)),
                ('torent_link_4k', models.CharField(blank=True, max_length=1000, null=True)),
                ('torent_link_1920', models.CharField(blank=True, max_length=1000, null=True)),
                ('torent_link_720', models.CharField(blank=True, max_length=1000, null=True)),
                ('torent_file_link', models.FileField(blank=True, null=True, upload_to='torent_movie')),
                ('tmvdbid', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
